"""Add lunch break columns to TimeLog

Revision ID: 0371f5a384fc
Revises: fb9025ae3d0d
Create Date: 2024-10-05 18:50:59.125877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0371f5a384fc'
down_revision = 'fb9025ae3d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_break_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lunch_break_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.drop_column('lunch_break_end')
        batch_op.drop_column('lunch_break_start')

    # ### end Alembic commands ###
