"""Add bathroom break columns to TimeLog

Revision ID: 6e2b8159a90c
Revises: 0371f5a384fc
Create Date: 2024-10-06 15:15:26.181501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2b8159a90c'
down_revision = '0371f5a384fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bathroom_break_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bathroom_break_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.drop_column('bathroom_break_end')
        batch_op.drop_column('bathroom_break_start')

    # ### end Alembic commands ###
