"""Add phone_number to Employee model

Revision ID: a7cb9882fbb6
Revises: 6e2b8159a90c
Create Date: 2024-10-06 18:27:00.476894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cb9882fbb6'
down_revision = '6e2b8159a90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
