"""Add status column to TimeLog model

Revision ID: f76782ee1ace
Revises: 8ce7481f38b5
Create Date: 2024-10-05 12:09:32.115830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76782ee1ace'
down_revision = '8ce7481f38b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
